# push will run on every pushed commit to any branch (so this will rerun the tests
# once a branch gets merged to main in addition to any new commits on any branch)
on: push

name: ARPA-H BDF Metadata Validate Tool

jobs:
  validate-tool:
    uses: ARPA-H-BDF/bdfkb-schema/.github/workflows/ci-validate.yaml@main
    with:
      python-version: '3.12'
